import CardProduct from "@/components/card-product";
import { useSession } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  const session = useSession();

  console.log(session);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen items-center justify-center gap-3">
        <CardProduct />
        <CardProduct />
        <CardProduct />
      </div>
    </>
  );
}
